--------------------------------------------------------
-- Archivo creado  - jueves-septiembre-05-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_DESCARGADOS
--------------------------------------------------------

   CREATE SEQUENCE  OPEN.FT_SEQ_DESCARGADOS  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 30321 CACHE 20 NOORDER  NOCYCLE ;
