--------------------------------------------------------
-- Archivo creado  - miércoles-mayo-06-2020   
--------------------------------------------------------


  CREATE TABLE "OPEN"."ARCHIVOS_PROCESS_LOG" 
   (	"PROCESS_USER" VARCHAR2(15 BYTE) DEFAULT USER, 
	"PROCESS_DATE" DATE DEFAULT SYSDATE, 
	"PROCESS_ID" NUMBER(*,0) PRIMARY KEY, 
	"PROCESS" VARCHAR2(200 BYTE), 
	"PROCESS_DESC" VARCHAR2(600 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TSD_DEFAULT" ;
--------------------------------------------------------
--  Constraints for Table ARCHIVOS_PROCESS_LOG
--------------------------------------------------------

  ALTER TABLE "OPEN"."ARCHIVOS_PROCESS_LOG" MODIFY ("PROCESS_DESC" NOT NULL ENABLE);
  ALTER TABLE "OPEN"."ARCHIVOS_PROCESS_LOG" MODIFY ("PROCESS" NOT NULL ENABLE);
  ALTER TABLE "OPEN"."ARCHIVOS_PROCESS_LOG" MODIFY ("PROCESS_ID" NOT NULL ENABLE);
  ALTER TABLE "OPEN"."ARCHIVOS_PROCESS_LOG" MODIFY ("PROCESS_DATE" NOT NULL ENABLE);
  ALTER TABLE "OPEN"."ARCHIVOS_PROCESS_LOG" MODIFY ("PROCESS_USER" NOT NULL ENABLE);
