
CREATE OR REPLACE AND COMPILE JAVA SOURCE NAMED 'FTDIR'
AS
  IMPORT JAVA.IO.*;
PUBLIC CLASS FTDIR EXTENDS OBJECT {
  PUBLIC STATIC VOID CREATE(STRING FTDIR) {
   FILE F = NEW FILE(FTDIR);
   F.MKDIR();
  }
}
;

CREATE OR REPLACE PROCEDURE JAVA_ARC(P IN VARCHAR2)
AS
LANGUAGE JAVA
NAME 'FTDIR.CREATE(JAVA.LANG.STRING)';
/;

--crear una carpeta solo para verficar que se tenga los permisos necesarios
EXECUTE JAVA_ARC('/OPENSMARTFLEX15/TEST_20200520/01');